openapi: 3.0.0
info:
  title: Line Bot Callback Status
  description: This document depicts the Line Bot callback status.
  version: 0.1
tags:
  - name: Hello World
paths:
  /callback:
    get:
      tags:
        - Hello World
      description: Get callback status
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
