site_name: Evolving Beasts

site_description: Evolving Beasts

site_author: 1chooo(Hugo ChunHo Lin)

site_url: https://1chooo.github.io/monster-bot/

repo_url: https://github.com/1chooo/monster-bot

copyright: Copyright &copy; 2023 1chooo (Hugo ChunHo Lin)

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.top
        - navigation.tabs
        # - navigation.sections
        # - navigation.indexes
        # - search.highlight
        # - navigation.expand
        # - navigation.tabs
    icon:
        logo: logo

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True
        execute: False
        # ignore: [""]
        # validate_nb: True
        #   ignore_h1_titles: True
        #   execute_ignore: "*.ipynb"

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: true
    - toc:
        permalink: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1chooo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/1chooo___

nav:
    - Home: index.md
    - Reference: reference.md
    - Report Issues: https://github.com/Weather-Shakespeare/monster-bot/issues